const MAJOR = "M"
const MAJOR_SEVENTH = "Mmaj7"
const MAJOR_SIXTH = "M6"

const MINOR = "m"
const MINOR_SEVENTH = "m7"
const MINOR_SIXTH = "m6"

const DOMINANT_SEVENTH = "M7"
const DOMINANT_SEVENTH_SHARP_FIVE = "M7#5"
const DOMINANT_NINTH = "M9"
const SUS_FOUR = "Msus4"

const MINOR_SEVENTH_FLAT_FIVE = "m7b5"



export const CHORD_FAMILIES = [
 MAJOR,
 MINOR,
 DOMINANT_SEVENTH,
 DOMINANT_SEVENTH_SHARP_FIVE,
 DOMINANT_NINTH,
 MINOR_SEVENTH,
 MAJOR_SEVENTH,
 MINOR_SEVENTH_FLAT_FIVE,
 MINOR_SIXTH,
 MAJOR_SIXTH,
 SUS_FOUR
]

export const CHORDS = [
  //--- major ---
  { name: "C",     notes: ["C1", "E1", "G1"],    family: MAJOR},
  { name: "C/E",   notes: ["E1", "G1", "C2"],    family: MAJOR},
  { name: "C/G",   notes: ["G1", "C2", "E2"],    family: MAJOR},
  { name: "Db",    notes: ["C#1", "F1", "G#1"],  family: MAJOR},
  { name: "Db/F",  notes: ["F1", "G#1", "C#2"],  family: MAJOR},
  { name: "Db/Ab", notes: ["G#1", "C#2", "F2"],  family: MAJOR},
  { name: "D",     notes: ["D1", "F#1", "A1"],   family: MAJOR},
  { name: "D/F#",  notes: ["F#1", "A1", "D2"],   family: MAJOR},
  { name: "D/A",   notes: ["A1", "D2", "F#2"],   family: MAJOR},
  { name: "Eb",    notes: ["D#1", "G1", "A#1"],  family: MAJOR},
  { name: "Eb/G",  notes: ["G1", "A#1", "D#2"],  family: MAJOR},
  { name: "Eb/Bb", notes: ["A#1", "D#2", "G2"],  family: MAJOR},
  { name: "E",     notes: ["E1", "G#1", "B1"],   family: MAJOR},
  { name: "E/G#",  notes: ["G#1", "B1", "E2"],   family: MAJOR},
  { name: "E/B",   notes: ["B1", "E2", "G#2"],   family: MAJOR},
  { name: "F",     notes: ["F1", "A1", "C2"],    family: MAJOR},
  { name: "F/A",   notes: ["A1", "C2", "F2"],    family: MAJOR},
  { name: "F/C",   notes: ["C1", "F1", "A1"],    family: MAJOR},
  { name: "F#",    notes: ["F#1", "A#1", "C#2"], family: MAJOR},
  { name: "F#/A#", notes: ["A#1", "C#2", "F#2"], family: MAJOR},
  { name: "F#/C#", notes: ["C#1", "F#1", "A#1"], family: MAJOR},
  { name: "G",     notes: ["G1", "B1", "D2"],    family: MAJOR},
  { name: "G/B",   notes: ["B1", "D2", "G2"],    family: MAJOR},
  { name: "G/D",   notes: ["D1", "G1", "B1"],    family: MAJOR},
  { name: "Ab",    notes: ["G#1", "C2", "D#2"],  family: MAJOR},
  { name: "Ab/C",  notes: ["C1", "D#1", "G#1"],  family: MAJOR},
  { name: "Ab/Eb", notes: ["D#1", "G#1", "C2"],  family: MAJOR},
  { name: "A",     notes: ["A1", "C#2", "E2"],   family: MAJOR},
  { name: "A/C#",  notes: ["C#1", "E1", "A1"],   family: MAJOR},
  { name: "A/E",   notes: ["E1", "A1", "C#2"],   family: MAJOR},
  { name: "Bb",    notes: ["A#1", "D2", "F2"],   family: MAJOR},
  { name: "Bb/D",  notes: ["D1", "F1", "A#1"],   family: MAJOR},
  { name: "Bb/F",  notes: ["F1", "A#1", "D2"],   family: MAJOR},
  { name: "B",     notes: ["B1", "D#2", "F#2"],  family: MAJOR},
  { name: "B/D#",  notes: ["D#1", "F#1", "B1"],  family: MAJOR},
  { name: "B/F#",  notes: ["F#1", "B1", "D#2"],  family: MAJOR},

    //--- maj7---
  { name: "Cmaj7/E",   notes: ["E1", "G1", "B1"],    family: MAJOR_SEVENTH},
  { name: "Cmaj7/G",   notes: ["G1", "B1", "E2"],    family: MAJOR_SEVENTH},
  { name: "Cmaj7/B",   notes: ["B1", "E2", "G2"],    family: MAJOR_SEVENTH},
  { name: "Dbmaj7/F",  notes: ["F1", "G#1", "C2"],   family: MAJOR_SEVENTH},
  { name: "Dbmaj7/Ab", notes: ["G#1", "C2", "F2"],   family: MAJOR_SEVENTH},
  { name: "Dbmaj7/C",  notes: ["C1", "F1", "G#1"],   family: MAJOR_SEVENTH},
  { name: "Dmaj7/F#",  notes: ["F#1", "A1", "C#2"],  family: MAJOR_SEVENTH},
  { name: "Dmaj7/A",   notes: ["A1", "C#2", "F#2"],  family: MAJOR_SEVENTH},
  { name: "Dmaj7/C#",  notes: ["C#1", "F#1", "A1"],  family: MAJOR_SEVENTH},
  { name: "Ebmaj7/G",  notes: ["G1", "A#1", "D2"],   family: MAJOR_SEVENTH},
  { name: "Ebmaj7/Bb", notes: ["A#1", "D2", "G2"],   family: MAJOR_SEVENTH},
  { name: "Ebmaj7/D",  notes: ["D1", "G1", "A#1"],   family: MAJOR_SEVENTH},
  { name: "Emaj7/G#",  notes: ["G#1", "B1", "D#2"],  family: MAJOR_SEVENTH},
  { name: "Emaj7/B",   notes: ["B1", "D#1", "G#1"],  family: MAJOR_SEVENTH},
  { name: "Emaj7/D#",  notes: ["D#1", "G#1", "B2"],  family: MAJOR_SEVENTH},
  { name: "Fmaj7/A",   notes: ["A1", "C2", "E2"],    family: MAJOR_SEVENTH},
  { name: "Fmaj7/C",   notes: ["C1", "E1", "A1"],    family: MAJOR_SEVENTH},
  { name: "Fmaj7/E",   notes: ["E1", "A1", "C2"],    family: MAJOR_SEVENTH},
  { name: "F#maj7/A#", notes: ["A#1", "C#2", "F2"],  family: MAJOR_SEVENTH},
  { name: "F#maj7/C#", notes: ["C#1", "F1", "A#1"],  family: MAJOR_SEVENTH},
  { name: "F#maj7/E#", notes: ["F1", "A#1", "C#2"],  family: MAJOR_SEVENTH},
  { name: "Gmaj7/B",   notes: ["B1", "D2", "F#2"],   family: MAJOR_SEVENTH},
  { name: "Gmaj7/D",   notes: ["D1", "F#1", "B1"],   family: MAJOR_SEVENTH},
  { name: "Gmaj7/F#",  notes: ["F#1", "B1", "D2"],   family: MAJOR_SEVENTH},
  { name: "Abmaj7/C",  notes: ["C1", "D#1", "G1"],   family: MAJOR_SEVENTH},
  { name: "Abmaj7/Eb", notes: ["D#1", "G1", "C2"],   family: MAJOR_SEVENTH},
  { name: "Abmaj7/G",  notes: ["G1", "C2", "D#2"],   family: MAJOR_SEVENTH},
  { name: "Amaj7/C#",  notes: ["C#1", "E1", "G#1"],  family: MAJOR_SEVENTH},
  { name: "Amaj7/E",   notes: ["E1", "G#1", "C#2"],  family: MAJOR_SEVENTH},
  { name: "Amaj7/G#",  notes: ["G#1", "C#2", "E2"],  family: MAJOR_SEVENTH},
  { name: "Bbmaj7/D",  notes: ["D1", "F1", "A1"],    family: MAJOR_SEVENTH},
  { name: "Bbmaj7/F",  notes: ["F1", "A1", "D2"],    family: MAJOR_SEVENTH},
  { name: "Bbmaj7/A",  notes: ["A1", "D2", "F2"],    family: MAJOR_SEVENTH},
  { name: "Bmaj7/D#",  notes: ["D#1", "F#1", "A#1"], family: MAJOR_SEVENTH},
  { name: "Bmaj7/F#",  notes: ["F#1", "A#1", "D#2"], family: MAJOR_SEVENTH},
  { name: "Bmaj7/A#",  notes: ["A#1", "D#2", "F#2"], family: MAJOR_SEVENTH},

  // major 6
  { name: "C6/A",   notes: ["A1", "C2", "E2"],    family: MAJOR_SIXTH},
  { name: "C6/C",   notes: ["C1", "E1", "A1"],    family: MAJOR_SIXTH},
  { name: "C6/E",   notes: ["E1", "A1", "C2"],    family: MAJOR_SIXTH},
  { name: "Db6/Bb", notes: ["A#1", "C#2", "F2"],  family: MAJOR_SIXTH},
  { name: "Db6",    notes: ["C#1", "F1", "A#1"],  family: MAJOR_SIXTH},
  { name: "Db6/F",  notes: ["F1", "A#1", "C#2"],  family: MAJOR_SIXTH},
  { name: "D6/B",   notes: ["B1", "D2", "F#2"],   family: MAJOR_SIXTH},
  { name: "D6",     notes: ["D1", "F#1", "B1"],   family: MAJOR_SIXTH},
  { name: "D6/F#",  notes: ["F#1", "B1", "D2"],   family: MAJOR_SIXTH},
  { name: "Eb6/C",  notes: ["C1", "D#1", "G1"],   family: MAJOR_SIXTH},
  { name: "Eb6",    notes: ["D#1", "G1", "C2"],   family: MAJOR_SIXTH},
  { name: "Eb6/G",  notes: ["G1", "C2", "D#2"],   family: MAJOR_SIXTH},
  { name: "E6/C#",  notes: ["C#1", "E1", "G#1"],  family: MAJOR_SIXTH},
  { name: "E6",     notes: ["E1", "G#1", "C#2"],  family: MAJOR_SIXTH},
  { name: "E6/G#",  notes: ["G#1", "C#2", "E2"],  family: MAJOR_SIXTH},
  { name: "F6/D",   notes: ["D1", "F1", "A1"],    family: MAJOR_SIXTH},
  { name: "F6",     notes: ["F1", "A1", "D2"],    family: MAJOR_SIXTH},
  { name: "F6/A",   notes: ["A1", "D2", "F2"],    family: MAJOR_SIXTH},
  { name: "F#6/D#", notes: ["D#1", "F#1", "A#1"], family: MAJOR_SIXTH},
  { name: "F#6",    notes: ["F#1", "A#1", "D#2"], family: MAJOR_SIXTH},
  { name: "F#6/A#", notes: ["A#1", "D#2", "F#2"], family: MAJOR_SIXTH},
  { name: "G6/E",   notes: ["E1", "G1", "B1"],    family: MAJOR_SIXTH},
  { name: "G6",     notes: ["G1", "B1", "E2"],    family: MAJOR_SIXTH},
  { name: "G6/B",   notes: ["B1", "E2", "G2"],    family: MAJOR_SIXTH},
  { name: "Ab6/F",  notes: ["F1", "G#1", "C2"],   family: MAJOR_SIXTH},
  { name: "Ab6",    notes: ["G#1", "C2", "F2"],   family: MAJOR_SIXTH},
  { name: "Ab6/C",  notes: ["C1", "F1", "G#1"],   family: MAJOR_SIXTH},
  { name: "A6/F#",  notes: ["F#1", "A1", "C#2"],  family: MAJOR_SIXTH},
  { name: "A6",     notes: ["A1", "C#2", "F#2"],  family: MAJOR_SIXTH},
  { name: "A6/C#",  notes: ["C#1", "F#1", "A1"],  family: MAJOR_SIXTH},
  { name: "Bb6/G",  notes: ["G1", "A#1", "D2"],   family: MAJOR_SIXTH},
  { name: "Bb6",    notes: ["A#1", "D2", "G2"],   family: MAJOR_SIXTH},
  { name: "Bb6/D",  notes: ["D1", "G1", "A#1"],   family: MAJOR_SIXTH},
  { name: "B6/G#",  notes: ["G#1", "B1", "D#2"],  family: MAJOR_SIXTH},
  { name: "B6",     notes: ["B1", "D#1", "G#1"],  family: MAJOR_SIXTH},
  { name: "B6/D#",  notes: ["D#1", "G#1", "B2"],  family: MAJOR_SIXTH},
  
  // sus4
  { name: "Csus4",     notes: ["C1", "F1", "G1"],    family: SUS_FOUR},
  { name: "Csus4/F",   notes: ["F1", "G1", "C2"],    family: SUS_FOUR},
  { name: "Csus4/G",   notes: ["G1", "C2", "F2"],    family: SUS_FOUR},
  { name: "Dbsus4",    notes: ["C#1", "F#1", "G#1"], family: SUS_FOUR},
  { name: "Dbsus4/Gb", notes: ["F#1", "G#1", "C#2"], family: SUS_FOUR},
  { name: "Dbsus4/Ab", notes: ["G#1", "C#2", "F#2"], family: SUS_FOUR},
  { name: "Dsus4",     notes: ["D1", "G1", "A1"],    family: SUS_FOUR},
  { name: "Dsus4/G",   notes: ["G1", "A1", "D2"],    family: SUS_FOUR},
  { name: "Dsus4/A",   notes: ["A1", "D2", "G2"],    family: SUS_FOUR},
  { name: "Ebsus4",    notes: ["D#1", "G#1", "A#1"], family: SUS_FOUR},
  { name: "Ebsus4/Ab", notes: ["G#1", "A#1", "D#2"], family: SUS_FOUR},
  { name: "Ebsus4/Bb", notes: ["A#1", "D#2", "G#2"], family: SUS_FOUR},
  { name: "Esus4",     notes: ["E1", "A1", "B1"],    family: SUS_FOUR},
  { name: "Esus4/A",   notes: ["A1", "B1", "E2"],    family: SUS_FOUR},
  { name: "Esus4/B",   notes: ["B1", "E2", "A2"],    family: SUS_FOUR},
  { name: "Fsus4",     notes: ["F1", "A#1", "C2"],   family: SUS_FOUR},
  { name: "Fsus4/Bb",  notes: ["A#1", "C2", "F2"],   family: SUS_FOUR},
  { name: "Fsus4/C",   notes: ["C1", "F2", "A#2"],   family: SUS_FOUR},
  { name: "F#sus4",    notes: ["F#1", "B1", "C#2"],  family: SUS_FOUR},
  { name: "F#sus4/B",  notes: ["B1", "C#2", "F#2"],  family: SUS_FOUR},
  { name: "F#sus4/C#", notes: ["C#1", "F#2", "B2"],  family: SUS_FOUR},
  { name: "Gsus4",     notes: ["G1", "C2", "D2"],    family: SUS_FOUR},
  { name: "Gsus4/C",   notes: ["C1", "D1", "G1"],    family: SUS_FOUR},
  { name: "Gsus4/D",   notes: ["D1", "G1", "C2"],    family: SUS_FOUR},
  { name: "Absus4",    notes: ["G#1", "C#2", "D#2"], family: SUS_FOUR},
  { name: "Absus4/Db", notes: ["C#1", "D#1", "G#1"], family: SUS_FOUR},
  { name: "Absus4/Eb", notes: ["D#1", "G#1", "C#2"], family: SUS_FOUR},
  { name: "Asus4",     notes: ["A1", "D2", "E2"],    family: SUS_FOUR},
  { name: "Asus4/D",   notes: ["D1", "E1", "A1"],    family: SUS_FOUR},
  { name: "Asus4/E",   notes: ["E1", "A1", "D2"],    family: SUS_FOUR},
  { name: "Bbsus4",    notes: ["A#1", "D#2", "F2"],  family: SUS_FOUR},
  { name: "Bbsus4/Eb", notes: ["D#1", "F1", "A#1"],  family: SUS_FOUR},
  { name: "Bbsus4/F",  notes: ["F1", "A#1", "D#2"],  family: SUS_FOUR},
  { name: "Bsus4",     notes: ["B1", "E2", "F#2"],   family: SUS_FOUR},
  { name: "Bsus4/E",   notes: ["E1", "F#1", "B1"],   family: SUS_FOUR},
  { name: "Bsus4/F#",  notes: ["F#1", "B1", "E2"],   family: SUS_FOUR},



  // 6/9
  //--- maj9 ---
  // add9
  // 7sus4

  // --- minor ---
  { name: "Cm",     notes: ["C1", "D#1", "G1"],   family: MINOR},
  { name: "Cm/Eb",  notes: ["D#1", "G1", "C2"],   family: MINOR},
  { name: "Cm/G",   notes: ["G1", "C2", "D#2"],   family: MINOR},
  { name: "C#m",    notes: ["C#1", "E1", "G#1"],  family: MINOR},
  { name: "C#m/E",  notes: ["E1", "G#1", "C#2"],  family: MINOR},
  { name: "C#m/G#", notes: ["G#1", "C#2", "E2"],  family: MINOR},
  { name: "Dm",     notes: ["D1", "F1", "A1"],    family: MINOR},
  { name: "Dm/F",   notes: ["F1", "A1", "D2"],    family: MINOR},
  { name: "Dm/A",   notes: ["A1", "D2", "F2"],    family: MINOR},
  { name: "Ebm",    notes: ["D#1", "F#1", "A#1"], family: MINOR},
  { name: "Ebm/Gb", notes: ["F#1", "A#1", "D#2"], family: MINOR},
  { name: "Ebm/Bb", notes: ["A#1", "D#2", "F#2"], family: MINOR},
  { name: "Em",     notes: ["E1", "G1", "B1"],    family: MINOR},
  { name: "Em/G",   notes: ["G1", "B1", "E2"],    family: MINOR},
  { name: "Em/B",   notes: ["B1", "E2", "G2"],    family: MINOR},
  { name: "Fm",     notes: ["F1", "G#1", "C2"],   family: MINOR},
  { name: "Fm/Ab",  notes: ["G#1", "C2", "F2"],   family: MINOR},
  { name: "Fm/C",   notes: ["C1", "F1", "G#1"],   family: MINOR},
  { name: "F#m",    notes: ["F#1", "A1", "C#2"],  family: MINOR},
  { name: "F#m/A",  notes: ["A1", "C#2", "F#2"],  family: MINOR},
  { name: "F#m/C#", notes: ["C#1", "F#1", "A1"],  family: MINOR},
  { name: "Gm",     notes: ["G1", "A#1", "D2"],   family: MINOR},
  { name: "Gm/Bb",  notes: ["A#1", "D2", "G2"],   family: MINOR},
  { name: "Gm/D",   notes: ["D1", "G1", "A#1"],   family: MINOR},
  { name: "Abm",    notes: ["G#1", "B1", "D#2"],  family: MINOR},
  { name: "Abm/Cb", notes: ["B1", "D#1", "G#1"],  family: MINOR},
  { name: "Abm/Eb", notes: ["D#1", "G#1", "B2"],  family: MINOR},
  { name: "Am",     notes: ["A1", "C2", "E2"],    family: MINOR},
  { name: "Am/C",   notes: ["C1", "E1", "A1"],    family: MINOR},
  { name: "Am/E",   notes: ["E1", "A1", "C2"],    family: MINOR},
  { name: "Bbm",    notes: ["A#1", "C#2", "F2"],  family: MINOR},
  { name: "Bbm/Db", notes: ["C#1", "F1", "A#1"],  family: MINOR},
  { name: "Bbm/F",  notes: ["F1", "A#1", "C#2"],  family: MINOR},
  { name: "Bm",     notes: ["B1", "D2", "F#2"],   family: MINOR},
  { name: "Bm/D",   notes: ["D1", "F#1", "B1"],   family: MINOR},
  { name: "Bm/F#",  notes: ["F#1", "B1", "D2"],   family: MINOR},

  //--- m6 ---
  { name: "Cm6/Eb",    notes: ["D#1", "G1", "A1"],  family: MINOR_SIXTH },
  { name: "Cm6/G",     notes: ["G1", "A1", "D#2"],  family: MINOR_SIXTH },
  { name: "Cm6/A",     notes: ["A1", "D#2", "G2"],  family: MINOR_SIXTH },
  { name: "C#m6/E",    notes: ["E1", "G#1", "A#1"], family: MINOR_SIXTH },
  { name: "C#m6/G#",   notes: ["G#1", "A#1", "E2"], family: MINOR_SIXTH },
  { name: "C#m6/A#",   notes: ["A#1", "E2", "G#2"], family: MINOR_SIXTH },
  { name: "Dm6/F",     notes: ["F1", "A1", "B1"],   family: MINOR_SIXTH },
  { name: "Dm6/A",     notes: ["A1", "B1", "F2"],   family: MINOR_SIXTH },
  { name: "Dm6/B",     notes: ["B1", "F2", "A2"],   family: MINOR_SIXTH },
  { name: "Ebm6/Gb",   notes: ["F#1", "A#1", "C2"], family: MINOR_SIXTH },
  { name: "Ebm6/Bb",   notes: ["A#1", "C2", "F#2"], family: MINOR_SIXTH },
  { name: "Ebm6/C",    notes: ["C1", "F#2", "A#2"], family: MINOR_SIXTH },
  { name: "Em6/G",     notes: ["G1", "B1", "C#2"],  family: MINOR_SIXTH },
  { name: "Em6/B",     notes: ["B1", "C#2", "G2"],  family: MINOR_SIXTH },
  { name: "Em6/C#",    notes: ["C#1", "G1", "B1"],  family: MINOR_SIXTH },
  { name: "Fm6/Ab",    notes: ["G#1", "C2", "D2"],  family: MINOR_SIXTH },
  { name: "Fm6/C",     notes: ["C1", "D1", "G#1"],  family: MINOR_SIXTH },
  { name: "Fm6/D",     notes: ["D1", "G#1", "C2"],  family: MINOR_SIXTH },
  { name: "F#m6/A",    notes: ["A1", "C#2", "D#2"], family: MINOR_SIXTH },
  { name: "F#m6/C#",   notes: ["C#1", "D#1", "A1"], family: MINOR_SIXTH },
  { name: "F#m6/D#",   notes: ["D#1", "A1", "C#2"], family: MINOR_SIXTH },
  { name: "Gm6/Bb",    notes: ["A#1", "D2", "E2"],  family: MINOR_SIXTH },
  { name: "Gm6/D",     notes: ["D1", "E1", "A#1"],  family: MINOR_SIXTH },
  { name: "Gm6/E",     notes: ["E1", "A#1", "D2"],  family: MINOR_SIXTH },
  { name: "Abm6/Cb",   notes: ["B1", "D#2", "F2"],  family: MINOR_SIXTH },
  { name: "Abm6/Eb",   notes: ["D#1", "F1", "B1"],  family: MINOR_SIXTH },
  { name: "Abm6/F",    notes: ["F1", "B1", "D#2"],  family: MINOR_SIXTH },
  { name: "Am6/C",     notes: ["C1", "E1", "F#1"],  family: MINOR_SIXTH },
  { name: "Am6/E",     notes: ["E1", "F#1", "C2"],  family: MINOR_SIXTH },
  { name: "Am6/F#",    notes: ["F#1", "C2", "E2"],  family: MINOR_SIXTH },
  { name: "Bbm6/Db",   notes: ["C#1", "F1", "G1"],  family: MINOR_SIXTH },
  { name: "Bbm6/F",    notes: ["F1", "G1", "C#2"],  family: MINOR_SIXTH },
  { name: "Bbm6/G",    notes: ["G1", "C#2", "F2"],  family: MINOR_SIXTH },
  { name: "Bm6/D",     notes: ["D1", "F#1", "G#1"], family: MINOR_SIXTH },
  { name: "Bm6/F#",    notes: ["F#1", "G#1", "D2"], family: MINOR_SIXTH },
  { name: "Bm6/G#",    notes: ["G#1", "D2", "F#2"], family: MINOR_SIXTH },

  //--- m7 ---
  { name: "Cm7/Eb",  notes: ["D#1", "G1", "A#1"],  family: MINOR_SEVENTH},
  { name: "Cm7/G",   notes: ["G1", "A#1", "D#2"],  family: MINOR_SEVENTH},
  { name: "Cm7/Bb",  notes: ["A#1", "D#2", "G2"],  family: MINOR_SEVENTH},
  { name: "C#m7/E",  notes: ["E1", "G#1", "B1"],   family: MINOR_SEVENTH},
  { name: "C#m7/G#", notes: ["G#1", "B1", "E2"],   family: MINOR_SEVENTH},
  { name: "C#m7/B",  notes: ["B1", "E2", "G#2"],   family: MINOR_SEVENTH},
  { name: "Dm7/F",   notes: ["F1", "A1", "C2"],    family: MINOR_SEVENTH},
  { name: "Dm7/A",   notes: ["A1", "C2", "F2"],    family: MINOR_SEVENTH},
  { name: "Dm7/C",   notes: ["C1", "F1", "A1"],    family: MINOR_SEVENTH},
  { name: "Ebm7/Gb", notes: ["F#1", "A#1", "C#2"], family: MINOR_SEVENTH},
  { name: "Ebm7/Bb", notes: ["A#1", "C#2", "F#2"], family: MINOR_SEVENTH},
  { name: "Ebm7/Db", notes: ["C#1", "F#1", "A#1"], family: MINOR_SEVENTH},
  { name: "Em7/G",   notes: ["G1", "B1", "D2"],    family: MINOR_SEVENTH},
  { name: "Em7/B",   notes: ["B1", "D2", "G2"],    family: MINOR_SEVENTH},
  { name: "Em7/D",   notes: ["D1", "G1", "B1"],    family: MINOR_SEVENTH},
  { name: "Fm7/Ab",  notes: ["G#1", "C2", "D#2"],  family: MINOR_SEVENTH},
  { name: "Fm7/C",   notes: ["C1", "D#1", "G#1"],  family: MINOR_SEVENTH},
  { name: "Fm7/Eb",  notes: ["D#1", "G#1", "C2"],  family: MINOR_SEVENTH},
  { name: "F#m7/A",  notes: ["A1", "C#2", "E2"],   family: MINOR_SEVENTH},
  { name: "F#m7/C#", notes: ["C#1", "E1", "A1"],   family: MINOR_SEVENTH},
  { name: "F#m7/E",  notes: ["E1", "A1", "C#2"],   family: MINOR_SEVENTH},
  { name: "Gm7/Bb",  notes: ["A#1", "D2", "F2"],   family: MINOR_SEVENTH},
  { name: "Gm7/D",   notes: ["D1", "F1", "A#1"],   family: MINOR_SEVENTH},
  { name: "Gm7/F",   notes: ["F1", "A#1", "D2"],   family: MINOR_SEVENTH},
  { name: "Abm7/Cb", notes: ["B1", "D#2", "F#2"],  family: MINOR_SEVENTH},
  { name: "Abm7/Eb", notes: ["D#1", "F#1", "B1"],  family: MINOR_SEVENTH},
  { name: "Abm7/Gb", notes: ["F#1", "B1", "D#2"],  family: MINOR_SEVENTH},
  { name: "Am7/C",   notes: ["C1", "E1", "G1"],    family: MINOR_SEVENTH},
  { name: "Am7/E",   notes: ["E1", "G1", "C2"],    family: MINOR_SEVENTH},
  { name: "Am7/G",   notes: ["G1", "C2", "E2"],    family: MINOR_SEVENTH},
  { name: "Bbm7/Db", notes: ["C#1", "F1", "G#1"],  family: MINOR_SEVENTH},
  { name: "Bbm7/F",  notes: ["F1", "G#1", "C#2"],  family: MINOR_SEVENTH},
  { name: "Bbm7/Ab", notes: ["G#1", "C#2", "F2"],  family: MINOR_SEVENTH},
  { name: "Bm7/D",   notes: ["D1", "F#1", "A1"],   family: MINOR_SEVENTH},
  { name: "Bm7/F#",  notes: ["F#1", "A1", "D2"],   family: MINOR_SEVENTH},
  { name: "Bm7/A",   notes: ["A1", "D2", "F#2"],   family: MINOR_SEVENTH},

  // m9

  // m11

  //--- dominant 7th ---
  { name: "C7/E",   notes: ["E1", "G1", "A#1"],  family: DOMINANT_SEVENTH},
  { name: "C7/G",   notes: ["G1", "A#1", "E2"],  family: DOMINANT_SEVENTH},
  { name: "C7/Bb",  notes: ["A#1", "E2", "G"],   family: DOMINANT_SEVENTH},
  { name: "Db7/F",  notes: ["F1", "G#1", "B1"],  family: DOMINANT_SEVENTH},
  { name: "Db7/Ab", notes: ["G#1", "B1", "F1"],  family: DOMINANT_SEVENTH},
  { name: "Db7/Cb", notes: ["B1", "F1", "G#1"],  family: DOMINANT_SEVENTH},
  { name: "D7/F#",  notes: ["F#1", "A1", "C2"],  family: DOMINANT_SEVENTH},
  { name: "D7/A",   notes: ["A1", "C2", "F#2"],  family: DOMINANT_SEVENTH},
  { name: "D7/C",   notes: ["C1", "F#1", "A1"],  family: DOMINANT_SEVENTH},
  { name: "Eb7/G",  notes: ["G1", "A#1", "C#2"], family: DOMINANT_SEVENTH},
  { name: "Eb7/Bb", notes: ["A#1", "C#2", "G2"], family: DOMINANT_SEVENTH},
  { name: "Eb7/Db", notes: ["C#1", "G1", "A#1"], family: DOMINANT_SEVENTH},
  { name: "E7/G#",  notes: ["G#1", "B1", "D2"],  family: DOMINANT_SEVENTH},
  { name: "E7/B",   notes: ["B1", "D2", "G#2"],  family: DOMINANT_SEVENTH},
  { name: "E7/D",   notes: ["D1", "G#1", "B1"],  family: DOMINANT_SEVENTH},
  { name: "F7/A",   notes: ["A1", "C2", "D#2"],  family: DOMINANT_SEVENTH},
  { name: "F7/C",   notes: ["C1", "D#1", "A1"],  family: DOMINANT_SEVENTH},
  { name: "F7/Eb",  notes: ["D#1", "A1", "C2"],  family: DOMINANT_SEVENTH},
  { name: "F#7/A#", notes: ["A#1", "C#2", "E2"], family: DOMINANT_SEVENTH},
  { name: "F#7/C#", notes: ["C#1", "E1", "A#1"], family: DOMINANT_SEVENTH},
  { name: "F#7/E",  notes: ["E1", "A#1", "C#2"], family: DOMINANT_SEVENTH},
  { name: "G7/B",   notes: ["B1", "D2", "F2"],   family: DOMINANT_SEVENTH},
  { name: "G7/D",   notes: ["D1", "F1", "B1"],   family: DOMINANT_SEVENTH},
  { name: "G7/F",   notes: ["F1", "B1", "D2"],   family: DOMINANT_SEVENTH},
  { name: "Ab7/C",  notes: ["C1", "D#1", "F#1"], family: DOMINANT_SEVENTH},
  { name: "Ab7/Eb", notes: ["D#1", "F#1", "C2"], family: DOMINANT_SEVENTH},
  { name: "Ab7/Gb", notes: ["F#1", "C2", "D#2"], family: DOMINANT_SEVENTH},
  { name: "A7/C#",  notes: ["C#1", "E1", "G1"],  family: DOMINANT_SEVENTH},
  { name: "A7/E",   notes: ["E1", "G1", "C#2"],  family: DOMINANT_SEVENTH},
  { name: "A7/G",   notes: ["G1", "C#2", "E2"],  family: DOMINANT_SEVENTH},
  { name: "Bb7/D",  notes: ["D1", "F1", "G#1"],  family: DOMINANT_SEVENTH},
  { name: "Bb7/F",  notes: ["F1", "G#1", "D2"],  family: DOMINANT_SEVENTH},
  { name: "Bb7/Ab", notes: ["G#1", "D2", "F2"],  family: DOMINANT_SEVENTH},
  { name: "B7/D#",  notes: ["D#1", "F#1", "A1"], family: DOMINANT_SEVENTH},
  { name: "B7/F#",  notes: ["F#1", "A1", "D#2"], family: DOMINANT_SEVENTH},
  { name: "B7/A",   notes: ["A1", "D#2", "F#2"], family: DOMINANT_SEVENTH},

  //--- 7#5 ---
  { name: "C7#5/E",     notes: ["E1", "G#1", "A#1"], family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "C7#5/G#",    notes: ["G#1", "A#1", "E2"], family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "C7#5/Bb",    notes: ["A#1", "E2", "G#2"], family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "Db7#5/F",    notes: ["F1", "A1", "B1"],   family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "Db7#5/A",    notes: ["A1", "B1", "F2"],   family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "Db7#5/Cb",   notes: ["B1", "F2", "A2"],   family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "D7#5/Gb",    notes: ["F#1", "A#1", "C2"], family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "D7#5/A#",    notes: ["A#1", "C2", "F#2"], family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "D7#5/C",     notes: ["C1", "F#2", "A#2"], family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "Eb7#5/G",    notes: ["G1", "B1", "C#2"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "Eb7#5/B",    notes: ["B1", "C#2", "G2"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "Eb7#5/Db",   notes: ["C#1", "G1", "B1"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "E7#5/G#",    notes: ["G#1", "C2", "D2"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "E7#5/B#",     notes: ["C1", "D1", "G#1"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "E7#5/D",     notes: ["D1", "G#1", "C2"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "F7#5/A",     notes: ["A1", "C#2", "D#2"], family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "F7#5/C#",    notes: ["C#1", "D#1", "A1"], family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "F7#5/Eb",    notes: ["D#1", "A1", "C#2"], family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "F#7#5/A#",   notes: ["A#1", "D2", "E2"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "F#7#5/D",    notes: ["D1", "E1", "A#1"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "F#7#5/E",    notes: ["E1", "A#1", "D2"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "G7#5/B",     notes: ["B1", "D#2", "F2"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "G7#5/D#",    notes: ["D#1", "F1", "B1"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "G7#5/F",     notes: ["F1", "B1", "D#2"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "Ab7#5/C",     notes: ["C1", "E1", "F#1"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "Ab7#5/E",     notes: ["E1", "F#1", "C2"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "Ab7#5/Gb",    notes: ["F#1", "C2", "E2"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "A7#5/C#",   notes: ["C#1", "F1", "G1"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "A7#5/E#",    notes: ["F1", "G1", "C#2"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "A7#5/G",    notes: ["G1", "C#2", "F2"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "Bb7#5/D",     notes: ["D1", "F#1", "G#1"], family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "Bb7#5/F#",    notes: ["F#1", "G#1", "D2"], family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "Bb7#5/G#",    notes: ["G#1", "D2", "F#2"], family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "B7#5/D#",    notes: ["D#1", "G1", "A1"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "B7#5/G",     notes: ["G1", "A1", "D#2"],  family: DOMINANT_SEVENTH_SHARP_FIVE },
  { name: "B7#5/A",     notes: ["A1", "D#2", "G2"],  family: DOMINANT_SEVENTH_SHARP_FIVE },

  //--- 7#9 ---

  // dominant 9th
  { name: "F#9/E",     notes: ["E1", "G#1", "A#1"], family: DOMINANT_NINTH },
  { name: "F#9/G#",    notes: ["G#1", "A#1", "E2"], family: DOMINANT_NINTH },
  { name: "F#9/A#",    notes: ["A#1", "E2", "G#2"], family: DOMINANT_NINTH },
  { name: "G9/F",      notes: ["F1", "A1", "B1"],   family: DOMINANT_NINTH },
  { name: "G9/A",      notes: ["A1", "B1", "F2"],   family: DOMINANT_NINTH },
  { name: "G9/B",      notes: ["B1", "F2", "A2"],   family: DOMINANT_NINTH },
  { name: "Ab9/Gb",    notes: ["F#1", "A#1", "C2"], family: DOMINANT_NINTH },
  { name: "Ab9/Bb",    notes: ["A#1", "C2", "F#2"], family: DOMINANT_NINTH },
  { name: "Ab9/C",     notes: ["C1", "F#2", "A#2"], family: DOMINANT_NINTH },
  { name: "A9/G",      notes: ["G1", "B1", "C#2"],  family: DOMINANT_NINTH },
  { name: "A9/B",      notes: ["B1", "C#2", "G2"],  family: DOMINANT_NINTH },
  { name: "A9/C#",     notes: ["C#1", "G1", "B1"],  family: DOMINANT_NINTH },
  { name: "Bb9/Ab",    notes: ["G#1", "C2", "D2"],  family: DOMINANT_NINTH },
  { name: "Bb9/C",     notes: ["C1", "D1", "G#1"],  family: DOMINANT_NINTH },
  { name: "Bb9/D",     notes: ["D1", "G#1", "C2"],  family: DOMINANT_NINTH },
  { name: "B9/A",      notes: ["A1", "C#2", "D#2"], family: DOMINANT_NINTH },
  { name: "B9/C#",     notes: ["C#1", "D#1", "A1"], family: DOMINANT_NINTH },
  { name: "B9/D#",     notes: ["D#1", "A1", "C#2"], family: DOMINANT_NINTH },
  { name: "C9/Bb",     notes: ["A#1", "D2", "E2"],  family: DOMINANT_NINTH },
  { name: "C9/D",      notes: ["D1", "E1", "A#1"],  family: DOMINANT_NINTH },
  { name: "C9/E",      notes: ["E1", "A#1", "D2"],  family: DOMINANT_NINTH },
  { name: "Db9/Cb",    notes: ["B1", "D#2", "F2"],  family: DOMINANT_NINTH },
  { name: "Db9/Eb",    notes: ["D#1", "F1", "B1"],  family: DOMINANT_NINTH },
  { name: "Db9/F",     notes: ["F1", "B1", "D#2"],  family: DOMINANT_NINTH },
  { name: "D9/C",      notes: ["C1", "E1", "F#1"],  family: DOMINANT_NINTH },
  { name: "D9/E",      notes: ["E1", "F#1", "C2"],  family: DOMINANT_NINTH },
  { name: "D9/F#",     notes: ["F#1", "C2", "E2"],  family: DOMINANT_NINTH },
  { name: "Eb9/Db",    notes: ["C#1", "F1", "G1"],  family: DOMINANT_NINTH },
  { name: "Eb9/F",     notes: ["F1", "G1", "C#2"],  family: DOMINANT_NINTH },
  { name: "Eb9/G",     notes: ["G1", "C#2", "F2"],  family: DOMINANT_NINTH },
  { name: "E9/D",      notes: ["D1", "F#1", "G#1"], family: DOMINANT_NINTH },
  { name: "E9/F#",     notes: ["F#1", "G#1", "D2"], family: DOMINANT_NINTH },
  { name: "E9/G#",     notes: ["G#1", "D2", "F#2"], family: DOMINANT_NINTH },
  { name: "F9/Eb",     notes: ["D#1", "G1", "A1"],  family: DOMINANT_NINTH },
  { name: "F9/G",      notes: ["G1", "A1", "D#2"],  family: DOMINANT_NINTH },
  { name: "F9/A",      notes: ["A1", "D#2", "G2"],  family: DOMINANT_NINTH },

  // dominant 13th
  // 7b9
  // 7b5

  //--- m7b5 ---
  { name: "Cm7b5/Eb",  notes: ["D#1", "F#1", "A#1"], family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Cm7b5/Gb",  notes: ["F#1", "A#1", "D#2"], family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Cm7b5/Bb",  notes: ["A#1", "D#2", "F#2"], family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "C#m7b5/E",  notes: ["E1", "G1", "B1"],    family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "C#m7b5/G",  notes: ["G1", "B1", "E2"],    family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "C#m7b5/B",  notes: ["B1", "E2", "G2"],    family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Dm7b5/F",   notes: ["F1", "G#1", "C2"],   family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Dm7b5/Ab",  notes: ["G#1", "C2", "F2"],   family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Dm7b5/C",   notes: ["C1", "F1", "G#1"],   family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "D#m7b5/F#", notes: ["F#1", "A1", "C#2"],  family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "D#m7b5/A",  notes: ["A1", "C#2", "F#2"],  family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "D#m7b5/C#", notes: ["C#1", "F#1", "A1"],  family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Em7b5/G",   notes: ["G1", "A#1", "D2"],   family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Em7b5/Bb",  notes: ["A#1", "D2", "G2"],   family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Em7b5/D",   notes: ["D1", "G1", "A#1"],   family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Fm7b5/Ab",  notes: ["G#1", "B1", "D#2"],  family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Fm7b5/Cb",  notes: ["B1", "D#1", "G#1"],  family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Fm7b5/Eb",  notes: ["D#1", "G#1", "B2"],  family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "F#m7b5/A",  notes: ["A1", "C2", "E2"],    family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "F#m7b5/C",  notes: ["C1", "E1", "A1"],    family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "F#m7b5/E",  notes: ["E1", "A1", "C2"],    family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Gm7b5/Bb",  notes: ["A#1", "C#2", "F2"],  family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Gm7b5/Db",  notes: ["C#1", "F1", "A#1"],  family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Gm7b5/F",   notes: ["F1", "A#1", "C#2"],  family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "G#m7b5/B",  notes: ["B1", "D2", "F#2"],   family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "G#m7b5/D",  notes: ["D1", "F#1", "B1"],   family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "G#m7b5/F#", notes: ["F#1", "B1", "D2"],   family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Am7b5/C",   notes: ["C1", "D#1", "G1"],   family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Am7b5/Eb",  notes: ["D#1", "G1", "C2"],   family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Am7b5/G",   notes: ["G1", "C2", "D#2"],   family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Bbm7b5/Db", notes: ["C#1", "E1", "G#1"],  family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Bbm7b5/Fb", notes: ["E1", "G#1", "C#2"],  family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Bbm7b5/Ab", notes: ["G#1", "C#2", "E2"],  family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Bm7b5/D",   notes: ["D1", "F1", "A1"],    family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Bm7b5/F",   notes: ["F1", "A1", "D2"],    family: MINOR_SEVENTH_FLAT_FIVE},
  { name: "Bm7b5/A",   notes: ["A1", "D2", "F2"],    family: MINOR_SEVENTH_FLAT_FIVE},

  // dim

]