export const PIANO_KEYS = [
  { class: "key white c", id: "C1"},
  { class: "key black c_sharp", id: "C#1"},
  { class: "key white d", id: "D1"},
  { class: "key black d_sharp", id: "D#1"},
  { class: "key white e", id: "E1"},
  { class: "key white f", id: "F1"},
  { class: "key black f_sharp", id: "F#1"},
  { class: "key white g", id: "G1"},
  { class: "key black g_sharp", id: "G#1"},
  { class: "key white a", id: "A1"},
  { class: "key black a_sharp", id: "A#1"},
  { class: "key white b", id: "B1"},
  { class: "key white c", id: "C2"},
  { class: "key black c_sharp", id: "C#2"},
  { class: "key white d", id: "D2"},
  { class: "key black d_sharp", id: "D#2"},
  { class: "key white e", id: "E2"},
  { class: "key white f", id: "F2"},
  { class: "key black f_sharp", id: "F#2"},
  { class: "key white g", id: "G2"},
  { class: "key black g_sharp", id: "G#2"},
  { class: "key white a", id: "A2"},
  { class: "key black a_sharp", id: "A#2"},
  { class: "key white b", id: "B2"},
]